# Generated by Django 6.0.2 on 2026-03-04 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['status'], name='friendships_status_cf67be_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user1', 'status'], name='friendships_user1_i_420b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user2', 'status'], name='friendships_user2_i_49950a_idx'),
        ),
    ]
